text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: "diagnostic"
    ssid:
      name: Connected SSID
      entity_category: "diagnostic"
    bssid:
      name: Connected BSSID
      entity_category: "diagnostic"
    mac_address:
      name: MAC Address
      entity_category: "diagnostic"
    dns_address:
      name: DNS Address
      entity_category: "diagnostic"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""